/*
 * ClickSend v3 API
 *  This is an official SDK for [ClickSend](https://clicksend.com)  Below you will find a current list of the available methods for clicksend.  *NOTE: You will need to create a free account to use the API. You can register [here](https://dashboard.clicksend.com/#/signup/step1/)..* 
 *
 * OpenAPI spec version: 3.1
 * Contact: support@clicksend.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package ClickSend.Api;

import ClickSend.Model.CreditCard;
import org.junit.Test;
import org.junit.Ignore;


import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for AccountRechargeApi
 */
@Ignore
public class AccountRechargeApiTest {

    private final AccountRechargeApi api = new AccountRechargeApi();

    
    /**
     * Get Credit Card info
     *
     * Get Credit Card info
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void rechargeCreditCardGetTest() throws Exception {
        String response = api.rechargeCreditCardGet();

        // TODO: test validations
    }
    
    /**
     * Update credit card info
     *
     * Update credit card info
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void rechargeCreditCardPutTest() throws Exception {
        CreditCard creditCard = null;
        String response = api.rechargeCreditCardPut(creditCard);

        // TODO: test validations
    }
    
    /**
     * Get list of all packages
     *
     * Get list of all packages
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void rechargePackagesGetTest() throws Exception {
        String country = null;
        String response = api.rechargePackagesGet(country);

        // TODO: test validations
    }
    
    /**
     * Purchase a package
     *
     * Purchase a package
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void rechargePurchaseByPackageIdPutTest() throws Exception {
        Integer packageId = null;
        String response = api.rechargePurchaseByPackageIdPut(packageId);

        // TODO: test validations
    }
    
    /**
     * Get specific Transaction
     *
     * Get specific Transaction
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void rechargeTransactionsByTransactionIdGetTest() throws Exception {
        String transactionId = null;
        String response = api.rechargeTransactionsByTransactionIdGet(transactionId);

        // TODO: test validations
    }
    
    /**
     * Purchase a package
     *
     * Get all transactions
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void rechargeTransactionsGetTest() throws Exception {
        Integer page = null;
        Integer limit = null;
        String response = api.rechargeTransactionsGet(page, limit);

        // TODO: test validations
    }
    
}
