/*
 * ClickSend v3 API
 *  This is an official SDK for [ClickSend](https://clicksend.com)  Below you will find a current list of the available methods for clicksend.  *NOTE: You will need to create a free account to use the API. You can register [here](https://dashboard.clicksend.com/#/signup/step1/)..* 
 *
 * OpenAPI spec version: 3.1
 * Contact: support@clicksend.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package ClickSend.Api;

import ClickSend.Model.Address;
import org.junit.Test;
import org.junit.Ignore;


import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for PostReturnAddressApi
 */
@Ignore
public class PostReturnAddressApiTest {

    private final PostReturnAddressApi api = new PostReturnAddressApi();

    
    /**
     * Delete specific post return address
     *
     * Delete specific post return address
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void postReturnAddressesByReturnAddressIdDeleteTest() throws Exception {
        Integer returnAddressId = null;
        String response = api.postReturnAddressesByReturnAddressIdDelete(returnAddressId);

        // TODO: test validations
    }
    
    /**
     * Get specific post return address
     *
     * Get specific post return address
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void postReturnAddressesByReturnAddressIdGetTest() throws Exception {
        Integer returnAddressId = null;
        String response = api.postReturnAddressesByReturnAddressIdGet(returnAddressId);

        // TODO: test validations
    }
    
    /**
     * Update post return address
     *
     * Update post return address
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void postReturnAddressesByReturnAddressIdPutTest() throws Exception {
        Integer returnAddressId = null;
        Address returnAddress = null;
        String response = api.postReturnAddressesByReturnAddressIdPut(returnAddressId, returnAddress);

        // TODO: test validations
    }
    
    /**
     * Get list of post return addresses
     *
     * Get list of post return addresses
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void postReturnAddressesGetTest() throws Exception {
        Integer page = null;
        Integer limit = null;
        String response = api.postReturnAddressesGet(page, limit);

        // TODO: test validations
    }
    
    /**
     * Create post return address
     *
     * Create post return address
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void postReturnAddressesPostTest() throws Exception {
        Address returnAddress = null;
        String response = api.postReturnAddressesPost(returnAddress);

        // TODO: test validations
    }
    
}
