/*
 * ClickSend v3 REST API
 *  This is the official [ClickSend](https://clicksend.com) SDK.  *You'll need to create a free account to use the API. You can register [here](https://www.clicksend.com/signup).*  You can use our API documentation along with the SDK. Our API docs can be found [here](https://developers.clicksend.com). 
 *
 * OpenAPI spec version: 3.1.0
 * Contact: support@clicksend.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package ClickSend.Api;

import ClickSend.ApiException;
import ClickSend.Model.DeliveryReceiptRule;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for SmsDeliveryReceiptRulesApi
 */
@Ignore
public class SmsDeliveryReceiptRulesApiTest {

    private final SmsDeliveryReceiptRulesApi api = new SmsDeliveryReceiptRulesApi();

    
    /**
     * Delete sms delivery receipt automation
     *
     * Delete sms delivery receipt automation
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void smsDeliveryReceiptAutomationDeleteTest() throws ApiException {
        Integer receiptRuleId = null;
        String response = api.smsDeliveryReceiptAutomationDelete(receiptRuleId);

        // TODO: test validations
    }
    
    /**
     * Get specific sms delivery receipt automation
     *
     * Get specific sms delivery receipt automation
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void smsDeliveryReceiptAutomationGetTest() throws ApiException {
        Integer receiptRuleId = null;
        String response = api.smsDeliveryReceiptAutomationGet(receiptRuleId);

        // TODO: test validations
    }
    
    /**
     * Create sms delivery receipt automations
     *
     * Create sms delivery receipt automations
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void smsDeliveryReceiptAutomationPostTest() throws ApiException {
        DeliveryReceiptRule deliveryReceiptRule = null;
        String response = api.smsDeliveryReceiptAutomationPost(deliveryReceiptRule);

        // TODO: test validations
    }
    
    /**
     * Update sms delivery receipt automation
     *
     * Update sms delivery receipt automation
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void smsDeliveryReceiptAutomationPutTest() throws ApiException {
        Integer receiptRuleId = null;
        DeliveryReceiptRule deliveryReceiptRule = null;
        String response = api.smsDeliveryReceiptAutomationPut(receiptRuleId, deliveryReceiptRule);

        // TODO: test validations
    }
    
    /**
     * Get all sms delivery receipt automations
     *
     * Get all sms delivery receipt automations
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void smsDeliveryReceiptAutomationsGetTest() throws ApiException {
        Integer page = null;
        Integer limit = null;
        String response = api.smsDeliveryReceiptAutomationsGet(page, limit);

        // TODO: test validations
    }
    
}
