/*
 * ClickSend v3 API
 *  This is an official SDK for [ClickSend](https://clicksend.com)  Below you will find a current list of the available methods for clicksend.  *NOTE: You will need to create a free account to use the API. You can register [here](https://dashboard.clicksend.com/#/signup/step1/)..* 
 *
 * OpenAPI spec version: 3.1
 * Contact: support@clicksend.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package ClickSend.Api;

import ClickSend.Model.UploadFile;
import org.junit.Test;
import org.junit.Ignore;


import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for UploadApi
 */
@Ignore
public class UploadApiTest {

    private final UploadApi api = new UploadApi();

    
    /**
     * Upload File
     *
     * Upload File
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void uploadsPostTest() throws Exception {
        UploadFile uploadFile = null;
        String convert = null;
        String response = api.uploadsPost(uploadFile, convert);

        // TODO: test validations
    }
    
}
