/*
 * ClickSend v3 REST API
 *  This is the official [ClickSend](https://clicksend.com) SDK.  *You'll need to create a free account to use the API. You can register [here](https://www.clicksend.com/signup).*  You can use our API documentation along with the SDK. Our API docs can be found [here](https://developers.clicksend.com). 
 *
 * OpenAPI spec version: 3.1.0
 * Contact: support@clicksend.com
 *
 * NOTE: This class is auto generated by the clicksend code generator program.
 * https://github.com/clicksend-api/clicksend-codegen.git
 * Do not edit the class manually.
 */


package ClickSend.Api;

import ClickSend.ApiException;
import ClickSend.Model.EmailTemplateNew;
import ClickSend.Model.EmailTemplateUpdate;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for UserEmailTemplatesApi
 */
@Ignore
public class UserEmailTemplatesApiTest {

    private final UserEmailTemplatesApi api = new UserEmailTemplatesApi();

    
    /**
     * Delete user email template
     *
     * Delete user email template
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void emailTemplateDeleteTest() throws ApiException {
        Integer templateId = null;
        String response = api.emailTemplateDelete(templateId);

        // TODO: test validations
    }
    
    /**
     * Get specific user email template
     *
     * Get specific user email templates
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void emailTemplateGetTest() throws ApiException {
        Integer templateId = null;
        String response = api.emailTemplateGet(templateId);

        // TODO: test validations
    }
    
    /**
     * Create email template
     *
     * Create email template
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void emailTemplatePostTest() throws ApiException {
        EmailTemplateNew emailTemplate = null;
        String response = api.emailTemplatePost(emailTemplate);

        // TODO: test validations
    }
    
    /**
     * Update email template
     *
     * Update email template
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void emailTemplatePutTest() throws ApiException {
        Integer templateId = null;
        EmailTemplateUpdate emailTemplate = null;
        String response = api.emailTemplatePut(templateId, emailTemplate);

        // TODO: test validations
    }
    
    /**
     * Get all user email templates
     *
     * Get all user email templates
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void emailTemplatesGetTest() throws ApiException {
        Integer page = null;
        Integer limit = null;
        String response = api.emailTemplatesGet(page, limit);

        // TODO: test validations
    }
    
}
