/*
 * ClickSend v3 API
 *  This is an official SDK for [ClickSend](https://clicksend.com)  Below you will find a current list of the available methods for clicksend.  *NOTE: You will need to create a free account to use the API. You can register [here](https://dashboard.clicksend.com/#/signup/step1/)..* 
 *
 * OpenAPI spec version: 3.1
 * Contact: support@clicksend.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package ClickSend.Api;

import ClickSend.Model.EmailTemplateNew;
import ClickSend.Model.EmailTemplateUpdate;
import org.junit.Test;
import org.junit.Ignore;


import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for UserEmailTemplatesApi
 */
@Ignore
public class UserEmailTemplatesApiTest {

    private final UserEmailTemplatesApi api = new UserEmailTemplatesApi();

    
    /**
     * Delete user email template
     *
     * Delete user email template
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void emailTemplateDeleteTest() throws Exception {
        Integer templateId = null;
        String response = api.emailTemplateDelete(templateId);

        // TODO: test validations
    }
    
    /**
     * Get specific user email template
     *
     * Get specific user email templates
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void emailTemplateGetTest() throws Exception {
        Integer templateId = null;
        String response = api.emailTemplateGet(templateId);

        // TODO: test validations
    }
    
    /**
     * Create email template
     *
     * Create email template
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void emailTemplatePostTest() throws Exception {
        EmailTemplateNew emailTemplate = null;
        String response = api.emailTemplatePost(emailTemplate);

        // TODO: test validations
    }
    
    /**
     * Update email template
     *
     * Update email template
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void emailTemplatePutTest() throws Exception {
        Integer templateId = null;
        EmailTemplateUpdate emailTemplate = null;
        String response = api.emailTemplatePut(templateId, emailTemplate);

        // TODO: test validations
    }
    
    /**
     * Get all user email templates
     *
     * Get all user email templates
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void emailTemplatesGetTest() throws Exception {
        Integer page = null;
        Integer limit = null;
        String response = api.emailTemplatesGet(page, limit);

        // TODO: test validations
    }
    
}
