/*
 * ClickSend v3 REST API
 *  This is the official [ClickSend](https://clicksend.com) SDK.  *You'll need to create a free account to use the API. You can register [here](https://www.clicksend.com/signup).*  You can use our API documentation along with the SDK. Our API docs can be found [here](https://developers.clicksend.com). 
 *
 * OpenAPI spec version: 3.1.0
 * Contact: support@clicksend.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.DeliveryIssue;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for DeliveryIssuesApi
 */
@Ignore
public class DeliveryIssuesApiTest {

    private final DeliveryIssuesApi api = new DeliveryIssuesApi();

    
    /**
     * Get all delivery issues
     *
     * Get all delivery issues
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void deliveryIssuesGetTest() throws ApiException {
        Integer page = null;
        Integer limit = null;
        String response = api.deliveryIssuesGet(page, limit);

        // TODO: test validations
    }
    
    /**
     * Create delivery Issue
     *
     * Create delivery Issue
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void deliveryIssuesPostTest() throws ApiException {
        DeliveryIssue deliveryIssue = null;
        String response = api.deliveryIssuesPost(deliveryIssue);

        // TODO: test validations
    }
    
}
