name: Publish Java Package
on:
  push:
    branches:
      - master

jobs:

  publish-gpr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Deploy to Github Package Registry
        run: mvn deploy -Dregistry=https://maven.pkg.github.com/ClickSend -Dtoken=${{ secrets.GPR_TOKEN }}
