name: Publish Java Package
on:
  push:
    branches:
      - master

jobs: 
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
    - name: Update Gradle wrapper and build config
      run: |
        sed -i 's|gradle-2.6-bin.zip|gradle-8.6-bin.zip|g' gradle/wrapper/gradle-wrapper.properties
        sed -i 's|^ *main = |       mainClass = |' build.gradle
        sed -i "s|compile '|implementation '|g" build.gradle
        sed -i "s|testCompile '|testImplementation '|g" build.gradle
    - name: Publish to Github registry
      env: 
        GPR_USER: ClickSend
        GPR_API_KEY: ${{ secrets.GPR_TOKEN }}
      run: chmod +x gradlew && ./gradlew publish
